export interface Model {
    orderid?: string, // generated by backend
    product: string,
    clientname: string,
    clientphone: string,
    ordersize: string,
    amount: string,
    orderdate?: string, // generated by backend
    status?: string // generated by backend
}