/**
 * DEMO-EDA-APP
 * YODA - Order API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: himanshu_sharma@manulife.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Defines a order information.
 */
export interface OrderInfo { 
    orderid: string;
    product?: string;
    clientname?: string;
    clientphone?: string;
    ordersize?: number;
    amount?: number;
    orderdate?: string;
    status?: string;
}
