/**
 * DEMO-EDA-APP
 * YODA - Order API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: himanshu_sharma@manulife.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { OrderInfo } from '../model/orderInfo';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class OrderService {

    protected basePath = 'https://atoaksserver.manulife.com/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Deletes an existing order
     * 
     * @param orderid order id to delete
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteOrderByID(orderid: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteOrderByID(orderid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteOrderByID(orderid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteOrderByID(orderid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (orderid === null || orderid === undefined) {
            throw new Error('Required parameter orderid was null or undefined when calling deleteOrderByID.');
        }

        let headers = this.defaultHeaders;

        // authentication (orderstore_auth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/order/delete/${encodeURIComponent(String(orderid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve details of Order
     * Returns a single OrderInfo
     * @param orderid ID of Order to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOrderByID(orderid: string, observe?: 'body', reportProgress?: boolean): Observable<OrderInfo>;
    public getOrderByID(orderid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OrderInfo>>;
    public getOrderByID(orderid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OrderInfo>>;
    public getOrderByID(orderid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (orderid === null || orderid === undefined) {
            throw new Error('Required parameter orderid was null or undefined when calling getOrderByID.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<OrderInfo>(`${this.basePath}/order/info/${encodeURIComponent(String(orderid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Updates a order in ML with form data
     * 
     * @param orderid ID of Order that needs to be updated
     * @param name Updated name of the order
     * @param status Updated status of the order
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateOrderForm(orderid: string, name?: string, status?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateOrderForm(orderid: string, name?: string, status?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateOrderForm(orderid: string, name?: string, status?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateOrderForm(orderid: string, name?: string, status?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (orderid === null || orderid === undefined) {
            throw new Error('Required parameter orderid was null or undefined when calling updateOrderForm.');
        }



        let headers = this.defaultHeaders;

        // authentication (orderstore_auth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/x-www-form-urlencoded'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (name !== undefined) {
            // formParams = formParams.append('name', <any>name) || formParams;
            formParams.append('name', <any>name)
        }
        if (status !== undefined) {
            // formParams = formParams.append('status', <any>status) || formParams;
            formParams.append('status', <any>status)
        }

        return this.httpClient.post<any>(`${this.basePath}/order/update/${encodeURIComponent(String(orderid))}`,
            convertFormParamsToString ? formParams.toString() : formParams,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
